# -*- coding: utf-8 -*-
"""playstoreproject1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1OO3qei4shDpYxwFHaGmF-gECSJDPCH
"""

# ==========================================
# Google Play Store Data Visualization
# Developed by: Aditi Srivastava
# Roll No.: 2401221550005
# ==========================================

import streamlit as st
import pandas as pd
import plotly.express as px

# -------------------------------
# Page Configuration
# -------------------------------
st.set_page_config(
    page_title="Google Play Store Dashboard",
    page_icon="📱",
    layout="wide"
)

# -------------------------------
# Custom CSS
# -------------------------------
st.markdown("""
<style>

.main{
    background-color:#f8f9fa;
}

.title{
    text-align:center;
    font-size:38px;
    font-weight:bold;
    color:#2E86C1;
}

.subtitle{
    text-align:center;
    color:gray;
    font-size:18px;
}

.card{
    background:white;
    padding:18px;
    border-radius:12px;
    text-align:center;
    box-shadow:0px 3px 8px rgba(0,0,0,0.15);
}

.footer{
    text-align:center;
    color:gray;
    font-size:15px;
}

</style>
""", unsafe_allow_html=True)

# -------------------------------
# Load Dataset
# -------------------------------
df = pd.read_csv("googleplaystore_v2.csv")

# -------------------------------
# Data Cleaning
# -------------------------------
df = df.drop_duplicates()

df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")
df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

df.dropna(subset=["Rating"], inplace=True)

# -------------------------------
# Header
# -------------------------------
st.markdown(
    '<p class="title">📱 Google Play Store Data Visualization Dashboard</p>',
    unsafe_allow_html=True
)

st.markdown(
    '<p class="subtitle">Explore insights from Google Play Store applications using interactive visualizations.</p>',
    unsafe_allow_html=True
)

st.divider()

# -------------------------------
# Student Details
# -------------------------------
st.info("""
👩‍🎓 **Developed By:** Aditi Srivastava

🆔 **Roll No.:** 2401221550005

🎓 **B.Tech CSE (IoT)**
""")

# -------------------------------
# KPI Cards
# -------------------------------
total_apps = len(df)
categories = df["Category"].nunique()
avg_rating = round(df["Rating"].mean(),2)
free_apps = len(df[df["Type"]=="Free"])

c1,c2,c3,c4 = st.columns(4)

with c1:
    st.metric("📱 Total Apps", total_apps)

with c2:
    st.metric("⭐ Average Rating", avg_rating)

with c3:
    st.metric("📂 Categories", categories)

with c4:
    st.metric("🆓 Free Apps", free_apps)

st.divider()
# =====================================================
# Sidebar
# =====================================================

st.sidebar.title("📋 Dashboard Menu")

option = st.sidebar.radio(
    "Navigate",
    [
        "Dataset Preview",
        "Visualizations"
    ]
)

st.sidebar.markdown("---")
st.sidebar.success("Google Play Store Analysis")
st.sidebar.write("👩‍🎓 Aditi Srivastava")
st.sidebar.write("🆔 Roll No.: 2401221550005")

# =====================================================
# Dataset Preview
# =====================================================

if option == "Dataset Preview":

    st.subheader("📄 Dataset Preview")

    st.dataframe(df.head(10), use_container_width=True)

    col1, col2 = st.columns(2)

    with col1:
        st.write("### Dataset Shape")
        st.write(f"Rows : **{df.shape[0]}**")
        st.write(f"Columns : **{df.shape[1]}**")

    with col2:
        st.write("### Missing Values")
        st.dataframe(df.isnull().sum())

# =====================================================
# Visualizations
# =====================================================

elif option == "Visualizations":

    st.subheader("📊 Interactive Visualizations")

    # -------------------------
    # Category Wise Apps
    # -------------------------

    category = (
        df["Category"]
        .value_counts()
        .head(10)
        .reset_index()
    )

    category.columns = ["Category", "Apps"]

    fig1 = px.bar(
        category,
        x="Category",
        y="Apps",
        color="Apps",
        title="Top 10 Categories by Number of Apps"
    )

    st.plotly_chart(fig1, use_container_width=True)

    # -------------------------
    # Rating Distribution
    # -------------------------

    fig2 = px.histogram(
        df,
        x="Rating",
        nbins=20,
        color_discrete_sequence=["royalblue"],
        title="Distribution of App Ratings"
    )

    st.plotly_chart(fig2, use_container_width=True)
        # -------------------------
    # Free vs Paid Apps
    # -------------------------

    st.subheader("🥧 Free vs Paid Apps")

    type_count = (
        df["Type"]
        .value_counts()
        .reset_index()
    )

    type_count.columns = ["Type", "Count"]

    fig3 = px.pie(
        type_count,
        names="Type",
        values="Count",
        hole=0.4,
        title="Distribution of Free and Paid Apps"
    )

    st.plotly_chart(fig3, use_container_width=True)

    # -------------------------
    # Top 10 Reviewed Apps
    # -------------------------

    st.subheader("🏆 Top 10 Most Reviewed Apps")

    top_reviews = (
        df.sort_values("Reviews", ascending=False)
        .head(10)
    )

    fig4 = px.bar(
        top_reviews,
        x="Reviews",
        y="App",
        orientation="h",
        color="Reviews",
        title="Most Reviewed Applications"
    )

    fig4.update_layout(yaxis={"categoryorder":"total ascending"})

    st.plotly_chart(fig4, use_container_width=True)

    # -------------------------
    # Correlation Heatmap
    # -------------------------

    st.subheader("🔥 Correlation Heatmap")

    corr = df[["Rating", "Reviews"]].corr()

    fig5 = px.imshow(
        corr,
        text_auto=True,
        color_continuous_scale="Blues",
        title="Correlation Matrix"
    )

    st.plotly_chart(fig5, use_container_width=True)

# =====================================================
# Footer
# =====================================================

st.divider()

st.markdown(
    """
    <div style="text-align:center;padding:15px;color:gray;">
        <h4>📱 Google Play Store Data Visualization Dashboard</h4>
        <p><b>Developed by:</b> Aditi Srivastava</p>
        <p><b>Roll No.:</b> 2401221550005</p>
        <p>B.Tech CSE (IoT)</p>
        <p>Shri Ramswaroop Memorial College of Engineering & Management</p>
    </div>
    """,
    unsafe_allow_html=True
)