# -*- coding: utf-8 -*-
"""starhealthinsurance10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1obVhck-sst50nl6Hh9E6TjtBploJvY_i
"""

!pip install streamlit
!pip install unstructured
!pip install langchain-openai==0.3.28
!pip install langchain-community==0.3.27
!pip install langchain-chroma==0.2.5
import streamlit as st
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.document_loaders import UnstructuredHTMLLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_core.prompts import ChatPromptTemplate

st.set_page_config(
    page_title="Star Health Insurance Chatbot",
    page_icon="🏥",
    layout="wide"
)

st.title("🏥 Star Health Insurance Assistant")
st.write("Ask questions related to Star Health Insurance policies.")

# -----------------------------
# Sidebar
# -----------------------------
st.sidebar.header("Configuration")

api_key = st.sidebar.text_input(
    "Enter OpenAI API Key",
    type="password",
    placeholder="sk-..."
)

if not api_key:
    st.info("Please enter your OpenAI API Key to continue.")
    st.stop()

# -----------------------------
# Load HTML Document
# -----------------------------
@st.cache_resource
def create_vectorstore(api_key):
    loader = UnstructuredHTMLLoader("starhealth.html")
    documents = loader.load()

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200
    )

    docs = splitter.split_documents(documents)

    embeddings = OpenAIEmbeddings(
        model="text-embedding-3-small",
        api_key=api_key
    )

    vectorstore = Chroma.from_documents(
        documents=docs,
        embedding=embeddings
    )

    return vectorstore

with st.spinner("Loading Star Health knowledge base..."):
    vectorstore = create_vectorstore(api_key)

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0,
    api_key=api_key
)

prompt = ChatPromptTemplate.from_template(
"""
You are an AI Healthcare Insurance Assistant for Star Health.

Answer the user's question ONLY using the provided context.

If the answer is not present in the context, reply:

"I couldn't find this information in the Star Health Insurance manual."

Context:
{context}

Question:
{question}

Answer:
"""
)

# -----------------------------
# Chat History
# -----------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# -----------------------------
# Chat Input
# -----------------------------
question = st.chat_input("Ask a question...")

if question:

    st.session_state.messages.append(
        {"role": "user", "content": question}
    )

    with st.chat_message("user"):
        st.markdown(question)

    docs = retriever.invoke(question)

    context = "\n\n".join(
        [doc.page_content for doc in docs]
    )

    final_prompt = prompt.format(
        context=context,
        question=question
    )

    with st.spinner("Thinking..."):
        response = llm.invoke(final_prompt)

    answer = response.content

    with st.chat_message("assistant"):
        st.markdown(answer)

    st.session_state.messages.append(
        {"role": "assistant", "content": answer}
    )