# -*- coding: utf-8 -*-
"""employepredictions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_qmC2izLIQ4Qet-uvhIyYgdz7GMpYDC
"""

pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    ConfusionMatrixDisplay,
    RocCurveDisplay
)

# -------------------------------
# Page Configuration
# -------------------------------

st.set_page_config(
    page_title="Employee Retention Prediction",
    page_icon="👨‍💼",
    layout="wide"
)

st.title("👨‍💼 Employee Retention Prediction")
st.write("Predict whether an employee is likely to leave the company.")

# -------------------------------
# Load Dataset
# -------------------------------

df = pd.read_csv("HR_comma_sep.csv")

# -------------------------------
# Data Preparation
# -------------------------------

subdf = df[['satisfaction_level',
            'average_montly_hours',
            'promotion_last_5years',
            'salary']]

salary_dummies = pd.get_dummies(subdf.salary, prefix='salary')

data = pd.concat([subdf, salary_dummies], axis=1)
data.drop('salary', axis=1, inplace=True)

X = data
y = df['left']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)

# -------------------------------
# Sidebar
# -------------------------------

st.sidebar.header("Employee Details")

satisfaction = st.sidebar.slider(
    "Satisfaction Level",
    0.00,
    1.00,
    0.50
)

hours = st.sidebar.slider(
    "Average Monthly Hours",
    80,
    320,
    200
)

promotion = st.sidebar.selectbox(
    "Promotion in Last 5 Years",
    [0,1]
)

salary = st.sidebar.selectbox(
    "Salary Level",
    ["low","medium","high"]
)

salary_low = 1 if salary=="low" else 0
salary_medium = 1 if salary=="medium" else 0
salary_high = 1 if salary=="high" else 0

input_data = pd.DataFrame({
    'satisfaction_level':[satisfaction],
    'average_montly_hours':[hours],
    'promotion_last_5years':[promotion],
    'salary_high':[salary_high],
    'salary_low':[salary_low],
    'salary_medium':[salary_medium]
})

# -------------------------------
# Prediction
# -------------------------------

st.subheader("Prediction")

if st.button("Predict"):

    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0]

    if prediction == 1:
        st.error("⚠️ Employee is likely to LEAVE the company.")
    else:
        st.success("✅ Employee is likely to STAY in the company.")

    st.write(f"**Probability of Staying:** {probability[0]*100:.2f}%")
    st.write(f"**Probability of Leaving:** {probability[1]*100:.2f}%")

# -------------------------------
# Model Accuracy
# -------------------------------

st.subheader("Model Accuracy")

st.metric(
    "Accuracy",
    f"{accuracy*100:.2f}%"
)

# -------------------------------
# Feature Importance
# -------------------------------

st.subheader("Feature Importance")

coef = pd.Series(
    model.coef_[0],
    index=X.columns
)

fig, ax = plt.subplots(figsize=(7,4))
coef.sort_values().plot(kind='barh', ax=ax)
ax.set_xlabel("Coefficient Value")
st.pyplot(fig)

# -------------------------------
# Confusion Matrix
# -------------------------------

st.subheader("Confusion Matrix")

y_pred = model.predict(X_test)

fig2, ax2 = plt.subplots(figsize=(5,5))

ConfusionMatrixDisplay.from_predictions(
    y_test,
    y_pred,
    ax=ax2
)

st.pyplot(fig2)

# -------------------------------
# ROC Curve
# -------------------------------

st.subheader("ROC Curve")

fig3, ax3 = plt.subplots(figsize=(5,5))

RocCurveDisplay.from_estimator(
    model,
    X_test,
    y_test,
    ax=ax3
)

st.pyplot(fig3)

# -------------------------------
# Dataset Preview
# -------------------------------

if st.checkbox("Show Dataset"):

    st.subheader("Dataset")

    st.dataframe(df)

# -------------------------------
# Dataset Statistics
# -------------------------------

if st.checkbox("Show Dataset Statistics"):

    st.subheader("Statistics")

    st.write(df.describe())

# -------------------------------
# Correlation Heatmap
# -------------------------------

if st.checkbox("Correlation Matrix"):

    st.subheader("Correlation")

    fig4, ax4 = plt.subplots(figsize=(8,6))

    corr = df.select_dtypes(include=['number']).corr()

    cax = ax4.matshow(corr)

    fig4.colorbar(cax)

    ax4.set_xticks(range(len(corr.columns)))
    ax4.set_yticks(range(len(corr.columns)))

    ax4.set_xticklabels(corr.columns, rotation=90)
    ax4.set_yticklabels(corr.columns)

    st.pyplot(fig4)

# -------------------------------
# Footer
# -------------------------------

st.markdown("---")
st.write("Developed using Streamlit | Logistic Regression")