# -*- coding: utf-8 -*-
"""mavevsfemaleusingcnnp7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWVxVi1AtX5lg_JeX7bXIIyPURrKeg5V
"""

!pip install streamlit
import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

st.set_page_config(page_title="Face Gender Classifier", page_icon="🧑", layout="wide")

# ---------- Load Model ----------
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("my_model.keras")

model = load_model()

IMG_SIZE = (150, 150)

# ---------- Header ----------
st.title("🧑 Face Gender Classification")
st.write("Upload a face image to predict the gender using a CNN model.")

st.divider()

col1, col2 = st.columns([1,1])

with col1:
    st.info("""
### 👩 Student Details

**Name:** Aditi Srivastava

**Roll No:** 2401221550005

**Course:** B.Tech CSE (IoT)
""")

with col2:
    st.success("""
### 📌 Project

- CNN Based Gender Classification
- TensorFlow / Keras
- Streamlit Deployment
""")

st.divider()

uploaded_file = st.file_uploader(
    "Upload Face Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file:

    image = Image.open(uploaded_file).convert("RGB")

    c1, c2 = st.columns(2)

    with c1:
        st.image(image, caption="Uploaded Image", use_container_width=True)

    img = image.resize(IMG_SIZE)
    img = np.array(img).astype("float32") / 255.0
    img = np.expand_dims(img, axis=0)

    with st.spinner("Predicting..."):
        prediction = model.predict(img, verbose=0)

    probability = float(prediction[0][0])

    # ---------- KEEPING YOUR LOGIC ----------
    if probability >= 0.5:
        result = "Male"
        confidence = probability * 100
    else:
        result = "Female"
        confidence = (1 - probability) * 100

    with c2:

        st.subheader("Prediction")

        if result == "Male":
            st.success(f"👨 {result}")
        else:
            st.info(f"👩 {result}")

        st.metric("Confidence", f"{confidence:.2f}%")

        st.progress(int(confidence))

        st.write(f"**Male :** {probability*100:.2f}%")
        st.write(f"**Female :** {(1-probability)*100:.2f}%")

else:
    st.warning("Please upload an image.")

# ---------- Sidebar ----------
st.sidebar.title("Model Information")

st.sidebar.write("""
**Algorithm:** CNN

**Framework:** TensorFlow

**Input Size:** 150 × 150

**Classes:** Male / Female

**Output:** Binary Classification
""")

st.sidebar.success("Model Loaded Successfully")

st.divider()

st.caption(
    "Developed by Aditi Srivastava | B.Tech CSE (IoT) | SRMCEM"
)